"""add sitter photo_url

Revision ID: 3096fbd01973
Revises: 48690bdbdb5e
Create Date: 2026-08-17 11:50:34.269747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3096fbd01973'
down_revision = '48690bdbdb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitter_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=300), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('sitter_profile', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
