"""initial schema

Revision ID: 48690bdbdb5e
Revises: 
Create Date: 2026-08-17 09:15:06.038735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48690bdbdb5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('sitter_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('offers_boarding', sa.Boolean(), nullable=True),
    sa.Column('offers_walking', sa.Boolean(), nullable=True),
    sa.Column('offers_daycare', sa.Boolean(), nullable=True),
    sa.Column('price_boarding_day', sa.Float(), nullable=True),
    sa.Column('price_walking_hour', sa.Float(), nullable=True),
    sa.Column('price_daycare_day', sa.Float(), nullable=True),
    sa.Column('max_dogs', sa.Integer(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('home_type', sa.String(length=50), nullable=True),
    sa.Column('has_yard', sa.Boolean(), nullable=True),
    sa.Column('accepts_puppies', sa.Boolean(), nullable=True),
    sa.Column('accepts_large_dogs', sa.Boolean(), nullable=True),
    sa.Column('availability_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('sitter_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sitter_profile_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_sitter_profile_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_sitter_profile_is_active'), ['is_active'], unique=False)

    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('sitter_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('dog_name', sa.String(length=80), nullable=True),
    sa.Column('dog_breed', sa.String(length=80), nullable=True),
    sa.Column('dog_size', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sitter_id'], ['sitter_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_sitter_id'), ['sitter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_status'), ['status'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_booking_id'), ['booking_id'], unique=False)

    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('sitter_profile_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sitter_profile_id'], ['sitter_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_sitter_profile_id'), ['sitter_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_sitter_profile_id'))

    op.drop_table('review')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_booking_id'))

    op.drop_table('message')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_status'))
        batch_op.drop_index(batch_op.f('ix_booking_sitter_id'))
        batch_op.drop_index(batch_op.f('ix_booking_owner_id'))

    op.drop_table('booking')
    with op.batch_alter_table('sitter_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sitter_profile_is_active'))
        batch_op.drop_index(batch_op.f('ix_sitter_profile_country'))
        batch_op.drop_index(batch_op.f('ix_sitter_profile_city'))

    op.drop_table('sitter_profile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
